#build environment
FROM node:16 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
#RUN yarn install react-scripts@1.1.1 -g --silent
COPY . /usr/src/app
RUN yarn install
RUN yarn build


FROM nginx:1.23.3-alpine
#use this when our build env is enabled.
COPY --from=builder /usr/src/app/out /var/www
#use this when our build env is disabled
#COPY ./build /var/www
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
# COPY public/explorer-settings.json /var/www
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
